name: Build and Deploy workflow
on: [push]
jobs:
  buils_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: action/checkout@v2
      - name: docker build
        run: docker build -t kubmark/hmwk26:$GITHUB_REF_NAME-$GITHUB_RUN_ID .

